.TH "morse-x" "1" "20060819" "Stephan Beyer" "hamradio"
.SH "NAME"
morse\-x \- morse practicing tool
.SH "SYNTAX"
.B morse\-x
[\fIoptions\fP]
.SH "DESCRIPTION"
.LP 
In
.B morse\-x
you can use any key on your keyboard 
as morse key (except \fBq\fR, which exits) and then it
displays your morsed stuff as readable text on stdout.
(You should execute morse\-x in an X terminal.)
.LP 
At the first start you will have to calibrate 
morse\-x, so please follow the instructions
on the console before pressing keys in the main window
wildly.
.SH "OPTIONS"
.LP 
Of course, morse\-x takes some options, some with
arguments. See the following list. A preceding dash (\-) is
optional.
.LP 
.TP 
\fBc\fR
Calibrate again, e.g. if the calibration of the first
execution was suboptimal.
.TP 
\fBf\fR \fIfrequency\fP
Set sound frequency.
.TP 
\fBg\fR
Show dits as red dots and daws as red lines in the 
main window.
.TP 
\fBh\fR
Print usage information, the same you can read here.
Hopefully.
.TP 
\fBm\fR
Mute audio. No audio device will be opened.
.TP 
\fBr\fR \fIsamplerate\fP
Set audio sample rate.
.TP 
\fBs\fR
Show dits as dots and daws as dashes on stdout.
.TP 
\fBv\fR \fIvolume\fP
Set sound volume.
.LP 
Note that older versions (2004*) were written using Xlib
instead of libSDL and thus had some other options and 
no audio output.
.SH "BUGS"
None so far. Please report some.
.SH "COPYRIGHT"
Copyright \(co 2004, 2006 Stephan Beyer <s\-beyer@gmx.net>
.LP
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
